name: libwasmvm
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
      - release/**

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}

defaults:
  run:
    working-directory: sei-wasmvm

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - release-build-alpine
          - release-build-linux
          - release-build-macos
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: |
          make ${{ matrix.target }}
      - name: Upload libraries
        uses: actions/upload-artifact@v5
        with:
          name: libwasmvm-${{ matrix.target }}-${{ github.sha }}
          path: internal/api/libwasmvm*
          if-no-files-found: warn